<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Stud" Member="Stud">
    <Type Name="Stud">
      <Column Name="studNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="studName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CounMaster" Member="CounMaster">
    <Type Name="CounMaster">
      <Column Name="CMID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="DeptNo" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CMQuest" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CMState" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Receiver" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="ContactDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CloseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ReceiverName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CounSubject" Member="CounSubject">
    <Type Name="CounSubject">
      <Column Name="CSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CSNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CSGroup" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CSItem" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CSText" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CSSeq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CounSubjectRecord" Member="CounSubjectRecord">
    <Type Name="CounSubjectRecord">
      <Column Name="CMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CSRValue" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>